# Generated by Django 5.2 on 2025-04-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='customizations',
        ),
        migrations.AddField(
            model_name='bot',
            name='initial_budget',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=20),
        ),
        migrations.AddField(
            model_name='bot',
            name='token_id',
            field=models.IntegerField(default=3375),
        ),
        migrations.AlterField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='infinite_event_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
