# Generated by Django 5.2 on 2025-04-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_bot_customizations_bot_initial_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='infinite_event_id',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='token_id',
        ),
        migrations.AddField(
            model_name='bot',
            name='buy_threshold',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='bot',
            name='order_value',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
        ),
        migrations.AddField(
            model_name='bot',
            name='price_interval',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='sell_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='bot',
            name='trade_interval',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='bot',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='initial_budget',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bot',
            name='trade_type',
            field=models.CharField(choices=[('live', 'Live'), ('backtesting', 'Backtesting')], default='live', max_length=12),
        ),
    ]
